### PR TITLE
Fix bug with arrays in query and formData with collectionFormat

### LINKED ISSUE #208: Array type parameters stringified from openapi->valid_input
An array type query parameter which contains strings for the items is being "stringified" upon calling the `openapi.valid_input` helper.

The parameter's definition:
image

The unexpected behavior where the dumped value both before and after the helper call is `$c->req->param('foo')`:
image

This began occurring with the release of version 4.00 of the plugin. I also tested with alternate versions of collectionFormats and found the only unaffected collectionFormat was `multi`.

Not 100% on this but I think the issue can be tracked down to the `_helper_validate` sub in the plugin:
[Version 3.41](https://metacpan.org/source/JHTHORSEN/Mojolicious-Plugin-OpenAPI-3.41/lib/Mojolicious/Plugin/OpenAPI.pm#L288)
[Version 4.02](https://metacpan.org/release/Mojolicious-Plugin-OpenAPI/source/lib/Mojolicious/Plugin/OpenAPI.pm#L256)

### PR DESCRIPTION
**Pull request by elcamlost**
Closes #208

### CODE REVIEW

File: lib/Mojolicious/Plugin/OpenAPI/Parameters.pm [hunk 1]
```diff
@@ -41,7 +41,8 @@ sub _helper_build_schema_request {
     formData => sub {
       my $name  = shift;
       my $value = $req->body_params->every_param($name);
-      return $evaluated[@evaluated] = {exists => 1, value => $value} if @$value;
+      my $cnt   = @$value;
```
Comment (jhthorsen) [inline lib/Mojolicious/Plugin/OpenAPI/Parameters.pm:44]: This is a minor, but can you change `$cnt` to just `$n`? (Same below)

**Review by jhthorsen — CHANGES_REQUESTED** [review]
I will merge this PR, but please change the variable names.

Great work, thank you! The tests made my day 😄

File: lib/Mojolicious/Plugin/OpenAPI/Parameters.pm (hunk 1 above)
Comment (elcamlost) [reply lib/Mojolicious/Plugin/OpenAPI/Parameters.pm]: Done
